{{- if .Values.metadataRbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ if .Values.metadataRbac.clusterAdmin }}ClusterRoleBinding{{- else }}RoleBinding{{- end }}
metadata:
  labels:
    dxp.cell/name: {{ include "dxpcell.name" . }}
    dxp.cell/instance: {{ .Release.Name }}
    dxp.cell/template-version: {{ .Chart.Version }}
    dxp.cell/managed-by: {{ .Release.Service }}
    dxp.module/name: {{ .Release.Name }}
    dxp.module/release-version: "{{ .Release.Revision }}"
    dxp.tenant/id: {{ .Values.global.tenantId }}
    dxp.domain/name: {{ .Values.global.domainName }}
    helm.sh/chart: {{ include "dxpcell.chart" . }}
    tenantId: {{ .Values.global.tenantId }}
  name: {{ include "dxpcell.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ if .Values.metadataRbac.clusterAdmin }}ClusterRole{{- else }}Role{{- end }}
  name: {{ include "dxpcell.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "dxpcell.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}