{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    dxp.cell/name: {{ include "dxpcell.name" . }}
    dxp.cell/instance: {{ .Release.Name }}
    dxp.cell/template-version: {{ .Chart.Version }}
    dxp.cell/managed-by: {{ .Release.Service }}
    dxp.module/name: {{ .Release.Name }}
    dxp.module/release-version: "{{ .Release.Revision }}"
    dxp.tenant/id: {{ .Values.global.tenantId }}
    dxp.domain/name: {{ .Values.global.domainName }}
    helm.sh/chart: {{ include "dxpcell.chart" . }}
    tenantId: {{ .Values.global.tenantId }}
  name: {{ include "dxpcell.serviceAccountName" . }}
{{- end }}