{{- if and ( .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" ) ( .Values.service.enabled ) }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "dxpcell.fullname" . }}-servicemonitor
  labels:
    prometheus: enabled
    dxp.cell/name: {{ include "dxpcell.name" . }}
    dxp.cell/instance: {{ .Release.Name }}
    dxp.cell/template-version: {{ .Chart.Version }}
    dxp.cell/managed-by: {{ .Release.Service }}
    dxp.module/name: {{ .Release.Name }}
    dxp.module/release-version: "{{ .Release.Revision }}"
    dxp.tenant/id: {{ .Values.global.tenantId }}
    dxp.domain/name: {{ .Values.global.domainName }}
    helm.sh/chart: {{ include "dxpcell.chart" . }}
    tenantId: {{ .Values.global.tenantId }}
spec:
  selector:
    matchLabels:
      dxp.cell/name: {{ include "dxpcell.name" . }}
      dxp.tenant/id: {{ .Values.global.tenantId }}
  endpoints:
    - port: http
      interval: 10s
      path: {{ .Values.monitoringPath }}
{{- end }}