# Default values for dxpcell template.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

podAutoscalerMinReplicas: 3
podAutoscalerMaxReplicas: 9
podAutoscalerMetrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 70

nameOverride: ""
fullnameOverride: ""

global:
  tenantId: development-template
  tenantDisplayName: Default tenant
  tenantAdminEmail: test@email
  domainName: generic

istio:
  enabled: true

serverless:
  enabled: false

service:
  enabled: false
  type: ClusterIP
  port: 80

serviceAccount:
  create: true

metadataRbac:
  create: false
  clusterAdmin: false

monitoringPath: /metrics

containers:
  - name: example-service
    image: "00000000001.dkr.ecr.us-east-2.amazonaws.com/example:latest"
    ports:
      - name: http
        containerPort: 80
    readinessProbe:
      httpGet:
        path: /health
        port: http
      initialDelaySeconds: 5
      timeoutSeconds: 3
      periodSeconds: 5
      failureThreshold: 2
    livenessProbe:
      httpGet:
        path: /health
        port: http
      initialDelaySeconds: 90
      timeoutSeconds: 3
      periodSeconds: 5
      failureThreshold: 5
    resources:
      requests:
        memory: 64Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 700m


  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []
